### Time Series Forcasting with Long Short-Term Memory 2

In this notebook I will investigate:
- univariate time series forcasting
- multivariate time series forcasting
- multi-step time series forcasting

time series forcasting.

This notebook is based on the tutorial by Jason Brownlee and here is the link to the tutorial
https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/


## Multivariate LSTM Models


In the case of multivariate time series, it means that we have more than one observation for each time step.

The problem can have Multiple Input Series or Multiple Parallel Series.

#### Multiple Input Series

In [4]:

# multivariate data preparation
import numpy as np
# define input sequence
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = np.array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = np.hstack((in_seq1, in_seq2, out_seq))
print(dataset)


[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]
